# PteroStats Configuration File
# Need help? Join our Discord server: https://discord.gg/zv6maQRah3
version: 5 # Warning: Do not change this unless you know what you are doing!

# Bot Presence Configuration
presence:
  enable: true
  text: "Hosting Panel" # The status text shown by the bot.
  type: "watching" # Available types: 'watching', 'playing', 'listening', 'competing'. (Note: 'streaming' is currently unsupported)
  status: "online" # Available types: 'online', 'idle', 'dnd', or 'invisible'

# Discord Channel and Refresh Timing Configuration
refresh: 10 # Interval in seconds for refreshing the bot's stats.
timeout: 5 # Timeout in seconds for node responses. Adjusting this will affect the overall refresh time.

# Message and Embed Configuration
# To disable an option, leave the value as an empty string: ''
message:
  content: "" # Custom content for bot messages. Set to '' to disable.
  attachment: "" # Attachments will delay stats refresh since they are uploaded first.

embed:
  panel:
    author:
      name: "Hosting Panel"
      icon: "" # Icon URL for the author of the panel embed.
    title: "Panel Stats" # Title of the panel stats embed.
    description: "Next update {{time}}" # Description for the panel. {{time}} will display the next refresh time.
    timestamp: false # Show the timestamp in the embed (true/false).
    color: "5865F2" # Embed color in hex format.
    footer:
      text: "" # Footer text. Set to '' to disable.
      icon: "" # Footer icon URL.
    thumbnail: "" # Thumbnail URL for the embed.
    image: "" # Image URL for the embed.

  nodes:
    author:
      name: "Hosting Panel"
      icon: "" # Icon URL for the author of the nodes embed.
    title: "Nodes Stats" # Title for the node stats embed.
    description: "" # Description for the node stats embed. Can be left empty.
    timestamp: true # Include a timestamp in the nodes embed (true/false).
    color: "5865F2" # Embed color in hex format.
    footer:
      text: "By @HirziDevs" # Footer text for node stats.
      icon: "" # Footer icon URL.
    thumbnail: "" # Thumbnail URL for the node stats embed.
    image: "" # Image URL for the node stats embed.

# Message Button Configuration
button:
  enable: true # Enable or disable buttons in messages.
  row1:
    - label: "Panel"
      url: "https://panel.example.com" # URL for the first button.
#    - label: "Dashboard" # Uncomment to add a second button.
#      url: "https://dash.example.com" # URL for the second button.

# Status Message Configuration
# For details on using custom emojis, visit: https://github.com/HirziDevs/PteroStats#using-custom-emoji
status:
  online: ":green_circle: Online" # Status message for when a node is online.
  offline: ":red_circle: Offline" # Status message for when a node is offline.

# Node Settings
# Instructions for retrieving node IDs: https://github.com/HirziDevs/PteroStats#blacklist-nodes
nodes_settings:
  blacklist: [] # Add node IDs to exclude them from the status embed (e.g., blacklist: [1]).
  details: true # Show node details such as memory and disk usage (true/false).
  servers: false # Show server details (true/false).
  allocations_as_max_servers: false # Show allocations as max servers (true/false).
  unit: "byte" # Unit for node usage, Available types: "byte" or "percentage".
  limit: 100 # Node limit for usage statistics display.

# Panel Users and Servers Settings
panel_settings:
  status: true # Display panel stats under node stats (true/false).
  servers: true # Display servers count (true/false).
  users: true # Display users count (true/false).

# Error Logging Configuration
# Enable logging to console if servers go offline, useful for debugging.
log_error: false # Set to true to enable error logging.
